import { MapMarker } from '@/features/map/mapMarkerTypes';

export const markers = [
    { id: 'Goodsprings', code: 'g00d', x: 34, y: 57, category: 'settlement' },
    { id: 'Goodsprings Cemetery', code: 'gc3m', x: 36, y: 54, category: 'cemetery' },
    { id: 'Primm', code: 'pr1m', x: 39, y: 74.5, category: 'settlement' },
    { id: 'Mojave Outpost', code: 'm00t', x: 29.7, y: 90, category: 'military' },
    { id: 'Nipton', code: 'n1pt', x: 45.5, y: 88, category: 'settlement' },
    { id: 'Novac', code: 'nv4c', x: 62.5, y: 68, category: 'settlement' },
    { id: 'NCRCF', code: 'ncrc', x: 45.3, y: 66.3, category: 'prison' },
    { id: 'New Vegas Strip', code: 'nvg5', x: 50, y: 27, category: 'city' },
    { id: 'Hoover Dam', code: 'h00v', x: 79.5, y: 50, category: 'dam' },
    { id: 'Jacobstown', code: 'j4ck', x: 22, y: 28, category: 'settlement' },
    { id: 'Red Rock Canyon', code: 'rrck', x: 33, y: 43, category: 'canyon' },
    { id: 'Black Mountain', code: 'bm0t', x: 57, y: 54, category: 'canyon' },
    { id: 'Hidden Valley', code: 'h1v4', x: 50.5, y: 59, category: 'bunker' },
    { id: 'Camp McCarran', code: 'cmcc', x: 50.5, y: 34, category: 'military' },
    { id: 'Boulder City', code: 'b0ul', x: 72.5, y: 51.5, category: 'settlement' },
    { id: 'Cottonwood Cove', code: 'c0tt', x: 76, y: 85.8, category: 'camp' },
    { id: 'The Fort', code: 'th4t', x: 84.5, y: 43.5, category: 'fortress' },
    { id: 'Bitter Springs', code: 'b15p', x: 79, y: 29.2, category: 'camp' },
    { id: 'Nelson', code: 'n3l5', x: 73.5, y: 68.5, category: 'settlement' },
    { id: 'Sloan', code: 'sl4n', x: 46.5, y: 55, category: 'settlement' },
    { id: 'Camp Searchlight', code: 'cmsl', x: 64.3, y: 88, category: 'hazard' },
    { id: 'Nellis Air Force Base', code: 'n4fb', x: 67, y: 17, category: 'military' },
    { id: 'Freeside East Gate', code: 'fr3g', x: 52.7, y: 25.2, category: 'city' },
    { id: 'Freeside North Gate', code: 'frng', x: 53, y: 22.5, category: 'city' },
    { id: 'Westside West Entrance', code: 'w3w3', x: 43, y: 22.2, category: 'city' },
    { id: 'Westside South Entrance', code: 'w3s3', x: 44.4, y: 23.6, category: 'city' },
    { id: 'Quarry Junction', code: 'quju', x: 45, y: 53, category: 'scrapyard' },
    { id: 'Gibson Scrap Yard', code: 'g1sy', x: 63.2, y: 64.5, category: 'scrapyard' },
    { id: 'HELIOS One', code: 'h3l1', x: 62.5, y: 58.2, category: 'industrial', iconKey: 'hazard' },
    { id: 'Camp Golf', code: 'c4g0', x: 64.7, y: 37.3, category: 'camp' },
    { id: 'Camp Forlorn Hope', code: 'c4fh', x: 74.7, y: 61.3, category: 'camp' },
    { id: 'Vault 22', code: 'vt22', x: 35, y: 21, category: 'vault' },
    { id: 'Vault 3', code: 'vt03', x: 44, y: 37.5, category: 'vault' },
    { id: 'Vault 34', code: 'vt34', x: 62.5, y: 31, category: 'vault' },
    { id: 'Vault 11', code: 'vt11', x: 64.5, y: 50.7, category: 'vault' },
    { id: 'Vault 19', code: 'vt19', x: 42.1, y: 45.7, category: 'vault' },
    { id: 'Vault 21', code: 'vt21', x: 48, y: 30, category: 'vault' },
    { id: 'North Vegas Square', code: 'nv3s', x: 51.2, y: 21.7, category: 'city' },
    { id: 'The Thorn', code: 't3th', x: 44.4, y: 25, category: 'fortress' },
    { id: "Legate's Camp", code: 'l3g4', x: 89.1, y: 51.8, category: 'camp' },
    { id: 'REPCONN Test Site', code: 'r3tt', x: 53.3, y: 67, category: 'industrial' },
    { id: 'REPCONN Headquarters', code: 'r3h3', x: 56.3, y: 44.3, category: 'industrial' },
    { id: "Follower's Outpost", code: 'f040', x: 61.3, y: 41.7, category: 'medical' },
    { id: 'Crimson Caravan Company', code: 'cc4c', x: 54.5, y: 23.5, category: 'store' },
    { id: 'Old Mormon Fort', code: '0mm4', x: 51.7, y: 23.5, category: 'medical' },
    { id: "King's School of Impersonation", code: 'ks01', x: 51, y: 25, category: 'school' },


    { id: '188 Trading Post', code: '188t', x: 65, y: 48, category: 'store' },
    { id: 'Aerotech Office Park', code: '4r0t', x: 55.8, y: 34, category: 'military' },
    { id: 'NCR Sharecropper Farms', code: 'ncrs', x: 53, y: 31, category: 'settlement' },
    { id: 'Ranger Station Charlie', code: 'rsc3', x: 57, y: 74, category: 'military' },
    { id: 'Ranger Station Foxtrot', code: 'rsfx', x: 34.5, y: 29, category: 'military' },

    { id: 'Silver Rush', code: 'slvr', x: 50, y: 24.5, category: 'store' },
    { id: 'Atomic Wrangler', code: 'at0m', x: 50.7, y: 24.3, category: 'store' },
] satisfies ReadonlyArray<MapMarker>;

